<?php
/**
 * Caridea
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * @copyright 2015 LibreWorks contributors
 * @license   http://opensource.org/licenses/Apache-2.0 Apache 2.0 License
 */
namespace Caridea\Random;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-30 at 13:10:14.
 */
class OpenSslTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Caridea\Random\OpenSsl::generate
     * @covers Caridea\Random\OpenSsl::isAvailable
     */
    public function testGenerate()
    {
        if (!extension_loaded('openssl')) {
            $this->markTestSkipped('These tests require the OpenSSL extension');
        }
        $object = new OpenSsl();
        $hash = $object->generate(32);
        $this->assertTrue(strlen($hash) == 32);
        
        $hash2 = $object->generate(128);
        $this->assertTrue(strlen($hash2) == 128);
        
        $hash3 = $object->generate(-1);
        $this->assertEmpty($hash3);
        
        $hash4 = $object->generate('foobar');
        $this->assertEmpty($hash4);
    }
}
